- name: Heroku
  apps:
  - name: gittip
  - name: gittip-dev
  - name: gittip-access-dashboard
  - name: building-gittip-com
  - name: roobot-test
  - name: roobot-prod
- name: GitHub
  apps:
  #- name: gittip/access-dashboard
  - name: gittip/building.gittip.com
  - name: gittip/Gittip-Everywhere
  - name: gittip/roobot
  - name: gittip/www.gittip.com
- name: Ally
  image:
  link:
  access:
  - whit537
- name: Balanced
  image:
  link:
  access:
  - whit537
  - clone1018
  - bruceadams
- name: Capital One
  image:
  link:
  access:
  - whit537
- name: DigitalOcean
  image:
  link:
  access:
  - whit537
- name: Freshdesk
  image:
  link:
  access:
  - whit537
- name: Gittip.com
  image:
  link:
  access:
  - whit537
- name: Gittip LLC
  image:
  link:
  access:
  - whit537
- name: Google Analytics
  image:
  link:
  access:
  - whit537
  - rummik
  - clone1018
  - abnor
  - seanlinsley
  - patcon
- name: New Alliance
  image:
  link:
  access:
  - whit537
- name: PayPal
  image:
  link:
  access:
  - whit537
- name: Sentry
  image:
  link:
  access:
  - whit537
  - clone1018
  - bruceadams
  - zwn
  - seanlinsley
- name: Tumblr
  image:
  link:
  access:
  - whit537
- name: Twitter
  image:
  link:
  access:
  - whit537
